language: php
sudo: false
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.composer/cache
notifications:
  email: false
env:
  - COMPOSER_DISABLE_XDEBUG_WARN=1
before_install:
  - phpenv config-rm xdebug.ini || true

matrix:
  fast_finish: true
  allow_failures:
    - name: Test with PHP 7.4
    - name: Test with PHP Nightly
  include:
    - name: Check coding style
      dist: precise
      php: "7.2"
      install:
        - travis_retry composer --no-interaction require --no-update --no-scripts friendsofphp/php-cs-fixer:^2.16.4
        - travis_retry composer --no-interaction install
      script:
        - composer --no-interaction codestyle -- --no-interaction --dry-run --diff -- .

    - name: Test with PHP 5.3
      dist: precise
      php: "5.3"
      install:
        - travis_retry composer --no-interaction install
      script:
        - composer --no-interaction test

    - name: Test with PHP 5.4
      dist: trusty
      php: "5.4"
      install:
        - travis_retry composer --no-interaction install
      script:
        - composer --no-interaction test

    - name: Test with PHP 5.5
      dist: trusty
      php: "5.5"
      install:
        - travis_retry composer --no-interaction install
      script:
        - composer --no-interaction test

    - name: Test with PHP 5.6
      php: "5.6"
      install:
        - travis_retry composer --no-interaction install
      script:
        - composer --no-interaction test

    - name: Test with PHP 7.0
      php: "7.0"
      install:
        - travis_retry composer --no-interaction install
      script:
        - composer --no-interaction test

    - name: Test with PHP 7.1
      php: "7.1"
      install:
        - travis_retry composer --no-interaction install
      script:
        - composer --no-interaction test

    - name: Test with PHP 7.2
      php: "7.2"
      install:
        - travis_retry composer --no-interaction install
      script:
        - composer --no-interaction test

    - name: Test with PHP 7.3
      php: "7.3"
      install:
        - travis_retry composer --no-interaction install
      script:
        - composer --no-interaction test

    - name: Test with PHP 7.4
      php: "7.4snapshot"
      install:
        - travis_retry composer --no-interaction install
      script:
        - composer --no-interaction test

    - name: Test with PHP Nightly
      php: nightly
      install:
        - composer --no-interaction config platform.php 7.4.0
        - travis_retry composer --no-interaction install
      script:
        - composer --no-interaction test
