name: PHPUnit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpunit:
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
          - windows-latest
        php-version:
          - "5.3"
          - "5.4"
          - "5.5"
          - "5.6"
          - "7.0"
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
        composer-version:
          - 1
          - 2
        include:
          - # Let's test agains an old Composer version
            operating-system: ubuntu-latest
            php-version: "5.3"
            composer-version: 1.7.2
        exclude:
          - # It seems that's not possible to install dependencies on Wihdows with PHP 5.3
            operating-system: windows-latest
            php-version: "5.3"
          - # It seems that's not possible to install dependencies on Wihdows with PHP 5.4
            operating-system: windows-latest
            php-version: "5.4"
    name: PHP ${{ matrix.php-version }} / Composer ${{ matrix.composer-version }} / ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          tools: composer:v${{ matrix.composer-version }}
      - name: Install dependencies
        run: composer --no-interaction --ansi install --no-progress --optimize-autoloader
      - name: Test
        run: composer --no-interaction --ansi run-script test -- --colors=always
